[build-system]
build-backend = "setuptools.build_meta"
requires      = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "amaanq12@gmail.com", name = "Amaan Qureshi" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "Doxygen grammar for tree-sitter"
keywords = [ "incremental", "parsing", "tree-sitter", "doxygen" ]
license.text = "MIT"
name = "tree-sitter-doxygen"
readme = "README.md"
requires-python = ">=3.10"
version = "1.1.0"

[project.urls]
Funding  = ""
Homepage = "https://github.com/tree-sitter-grammars/tree-sitter-doxygen"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build          = "cp310-*"
build-frontend = "build"
