name: Fuzz scanner

on:
  push:
    branches: [master]
    paths:
      - src/scanner.c
  pull_request:
    branches: [master]
    paths:
      - src/scanner.c

jobs:
  fuzz:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run the fuzzer
        uses: tree-sitter/fuzz-action@v4
